### ISSUE TITLE
Add option to install directly from crates.io in README

### ISSUE THREAD

**Issue by Ebedthan** [kornelski/dssim#111]
Hi @kornelski,

Thanks for the nice tools.

I think it would be useful especially for Rust newcomers to know that they can install dssim directly from crates.io using a single command like `cargo install dssim` to be done.

I can prepare a PR if you want.

Best,
Anicet

**Comment by kornelski** [comment]
I've realized I've neglected the releases page, which was needed for binaries. I've released updated binaries instead. 

I'd rather not recommend building straight from crates.io — cargo isn't a proper system-level package manager.
