### ISSUE TITLE
Broken AVIF feature

### ISSUE THREAD

**Issue by UnKnoWn-Consortium** [kornelski/dssim#112]
I noticed that AVIF was (finally!) a feature listed in the ```Cargo.toml```. I tried to compile a version with that option enabled but to no avail. The compilation process throws a E0061 "invalid number of arguments" error in line 16 of ```avif.rs``` in the crate ```load_image```. 

I filled the missing argument with a ```vec![]``` and it compiles. It is now working like a charm. 

The repo for the ```load_image``` crate is nowhere to be found, so forgive me for posting it as an issue here.

**Comment by kornelski** [comment]
Fixed. Run `cargo update` and try again.

**Comment by UnKnoWn-Consortium** [comment]
wow that's quick. I can confirm it works now. Thanks a lot!
