### ISSUE TITLE
Cannot be used for WASM because of multithreading?

### ISSUE THREAD

**Issue by liafuzho** [kornelski/dssim#114]
When I call "create_image" function in WASM It's frustrating to get an error and exit.

**Comment by kornelski** [comment]
[Unfortunately](https://github.com/rayon-rs/rayon/issues/861)

In browsers that support threads, maybe this will work: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon

**Comment by kornelski** [comment]
Done in 3.2.0. Disable the `threads` feature.

**Comment by RReverser** [comment]
> In browsers that support threads, maybe this will work: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon

FWIW this also should work indeed and usually provides noticeable perf improvements, like multithreading on any other platform. Although it does require a bit of fiddling with configs.
