### ISSUE TITLE
Feature Request: Add an examples folder 

### ISSUE THREAD

**Issue by alphastrata** [kornelski/dssim#118]
Would be great if there were some examples of how to use this 'as a library'.

Great app :)

**Comment by kornelski** [comment]
Hopefully the main binary is an example itself:

https://github.com/kornelski/dssim/blob/435391b3620fe3a7fc18595ad2304564ab501f6a/src/main.rs#L80-L106

**Comment by alphastrata** [comment]
Fair enough -- thanks for responding.
