### ISSUE TITLE
[Help] How to simply compare two JPEG images in memory

### ISSUE THREAD

**Issue by azureqaq** [kornelski/dssim#130]
Hi, I'm trying to use this crate in my project, but since I'm new to rust, I'm having some problems.
I have `Bytes` data of two jpeg images in memory, now I want to compare the `&Bytes` of the original image with the `&Bytes` of the other image and finally get an f64.
I would appreciate if you could provide some ideas.
Sample code would be nice.
Sorry for disturbing.

**Comment by azureqaq** [comment]
They are not the same size

**Comment by kornelski** [comment]
You'll need to decode them first, see https://lib.rs/load_image and if they're not the same pixel size, then the comparison is going to be weird. You'll have to resize them both to the same size first, see https://lib.rs/resize.

**Comment by azureqaq** [comment]
thank you very much! 👀
