### ISSUE TITLE
Question: Can a shared library be built?

### ISSUE THREAD

**Issue by th0ma7** [kornelski/dssim#131]
Looking into integrating dssim to a gstreamer|ffmpeg project for Synology NAS.
https://github.com/SynoCommunity/spksrc/pull/5298

I was able to build the binary with no issue so far.

My question is, in your README you refer to it being also available as library.  Is there an option to pass to generate the library and install the include files?

Thnx.

**Comment by kornelski** [comment]
I haven't added a C interface for it. Currently it's a Rust library for Rust projects, and its public API uses generic types/traits that are impossible to express in a C header file.

You could write your own small wrapper for dssim in Rust, which does whatever comparison you want, and makes it available through your custom `extern "C"` function that the rest of your code can call. If you compile that with [`crate-type = ["cdylib"]`](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#library) or use [`cargo-c`](//lib.rs/cargo-c) you can build a proper C-compatible dynamically-linked library.

**Comment by th0ma7** [comment]
Thnx, that explains.  And I figured that gstreamer simply checks for the existence of the binary and does not bind to any library pertaining to it.  So my overall build looks good.
