### ISSUE TITLE
version `GLIBC_2.18' not found

### ISSUE THREAD

**Issue by ayroblu** [kornelski/dssim#137]
Hi, I was wondering if there's some kind of workaround for this. I'm guessing there's some shared libraries that you're depending on that aren't available on my version of linux (centos 7):

```
./dssim: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by ./dssim)
```

Thanks,
Ben

**Comment by kornelski** [comment]
This binary requires an OS from at least 2013, and yours hasn't been updated since 2009. I don't support such old systems.
