### ISSUE TITLE
How do I install dssim.h into the prefix?

### ISSUE THREAD

**Issue by intractabilis** [kornelski/dssim#139]
Building GStreamer 1.22 gives the following error:
```
../gstreamer/subprojects/gst-plugins-bad/ext/iqa/iqa.c:67:10: fatal error: dssim.h: No such file or directory
   67 | #include "dssim.h"
      |          ^~~~~~~~~
```
I am not familiar with Rust, and your `README.md` doesn't provide any details on how to install the library and the C header files into the prefix. Can you provide details on how to fix the error above?

**Comment by kornelski** [comment]
Rust doesn't even know headers exist and has no support for installing anything C-related. You need to copy the C header yourself wherever your OS/compiler wants it.

**Comment by kornelski** [comment]
https://github.com/kornelski/dssim/commit/a856bfa31c749f1239e8ad45332884a8f3c04bcb

**Comment by intractabilis** [comment]
> Rust doesn't even know headers exist and has no support for installing anything C-related.

I never assumed it does. Thank you for updating `README.md`.

**Comment by intractabilis** [comment]
I've tried the instructions. I've got the following error:
```
$ cargo cinstall --release --prefix=${HOME}/gcc-env
Error: CliError { error: Some(Package `dssim-core v3.2.5 (/somewhere/dssim/dssim-core)` does not have the feature `capi`), exit_code: 101 }
```
