### ISSUE TITLE
Ranking 

### ISSUE THREAD

**Issue by gedw99** [kornelski/dssim#147]
Hey 

i habe 1000 of Images that I need to compare against 1 image to find a match . 

so does the api allow to return a ranking based on each run I do ?

I can then remember the higher rank out of all of them and return that are the closest match.

**Comment by kornelski** [comment]
It allows reusing the one image to compare against. Picking the best result is left as an exercise for the reader.

**Comment by gedw99** [comment]
Thanks @kornelski 

Ranking -ok sure.
