### ISSUE TITLE
Wasm

### ISSUE THREAD

**Issue by gedw99** [kornelski/dssim#148]
Would make it easier for me to use if I can compile it as wasm.

Anyone know how to do that ? Am not a rust expert but with rust I think it’s pretty easy by adding the right wasm export annotations to the rust functions we want exported.

then I can use it as part of a bigger system.

the wasm host runner will need to feed each image in as a byte array or similar because the wasm guest ( the rust code ) does not have access to the file system or network.

**Comment by gedw99** [comment]
I just saw that this code is already designed to compile to wasm.

dors it allow passing in the images as byte array though ?

**Comment by kornelski** [comment]
The command-line version that takes PNG/JPEG files is not supported in WASM. 

The library interface of https://docs.rs/dssim-core/latest/dssim_core/ is supported in WASM. It's up to you how to load images. The library takes raw pixels:

https://docs.rs/dssim-core/latest/dssim_core/struct.Dssim.html#method.create_image_rgba

**Comment by gedw99** [comment]
Right .. thats @kornelski 

I am not great at rust, and can't work out how to do that.

**Comment by unclesmiley** [comment]
@gedw99 You can try [this](https://github.com/kingcc/ssime) project, which is a port version of this project.
