### ISSUE TITLE
lieon.rs license

### ISSUE THREAD

**Issue by milot-mirdita** [kornelski/dssim#159]
I would like to use `lieon.rs` in a GPLv3 project. Would you consider re-licensing this single file? 

For context:  I am integrating the [ProstT5](https://github.com/mheinzinger/ProstT5) language model into [Foldseek](https://github.com/steineggerlab/foldseek) using the Candle ML framework. I want to only parallelize from the C++ side and not rely on any parallelization within Rust. I found the shim here: https://github.com/rayon-rs/rayon/issues/861 and extended it slightly to work for me (https://gist.github.com/milot-mirdita/3bd47a2abc58384903dda0ec86d0d07b).

**Comment by kornelski** [comment]
I've relicensed it. There's also https://lib.rs/crates/maybe-rayon

**Comment by milot-mirdita** [comment]
Thanks a lot! I didn't know about maybe-rayon, that would have saved me some time figuring out this scope thing.
