### ISSUE TITLE
Problem with Rust release under windows, -o option creates 4 small pics.

### ISSUE THREAD

**Issue by jalba69** [kornelski/dssim#45]
Hello,

I tried the last version dssim-2.8.0 using Rust released and found a small issue , for now i'm not sure what is going on.

On previous version 1.3.2 comparing two .png's with the option -o to visualize the difference was giving me this : 
original
![original](https://user-images.githubusercontent.com/15131985/35291131-a2b05650-006c-11e8-88ab-9159dd95ba21.png)
modified
![modified](https://user-images.githubusercontent.com/15131985/35291149-b021cd8c-006c-11e8-800b-253de1518251.png)
-o option to visualize the differences : 
![dssim_23_01_2018-18-40-03__0 00289185](https://user-images.githubusercontent.com/15131985/35291214-f51b037c-006c-11e8-94f6-ae48c677ac34.png)

Now using the new 2.8.0 provided windows .exe  in the release page and comparing the two same images  it creates 4 small pictures with the size decreasing when i use the -o option, this is what i get :
![result png-0](https://user-images.githubusercontent.com/15131985/35291493-be069724-006d-11e8-8409-2ba38e56b86b.png)
![result png-1](https://user-images.githubusercontent.com/15131985/35291494-be283f28-006d-11e8-84ce-90a9e0613bae.png)
![result png-2](https://user-images.githubusercontent.com/15131985/35291496-be47b51a-006d-11e8-82c7-981362086a6f.png)
![result png-3](https://user-images.githubusercontent.com/15131985/35291498-be6a8b58-006d-11e8-9cd5-ffea5aca168e.png)

The DSSIM score :  
v1.3.2 score = 0.00289185
v2.8.0 score = 0.10827

Well i'm lost with the 4 pictures created, i don't understand
If it helps i'm under win7 x64.

And thanks a lot for this nice little tool, something i use regularly and very helpful :)

_Edited original post :
 found out what was the issue for the second problem i reported when using a bat file, silly me... so i just removed this unnecessary part, remains the creation of those 4 small pictures now._

Thank you.

**Comment by kornelski** [comment]
The 4 images are comparisons at different scales/resolutions. These are differences visible from various viewing distances.

I suspect the writing permission denied error is caused by Windows Smartscreen or similar quarantine feature. I find that executable built locally can write, but the same executable downloaded from the internet can't. I don't know what to do about it other than paying about $150/year for a Microsoft exe signing certificate.

**Comment by jalba69** [comment]
Thank you for the quick reply.

I understand now why the 4 pics for various viewing distances but the input pictures i used for the comparison were 1280x522 px and the biggest output picture was 16x65 px only, the smallest one was 20x8 px.

Here i put the 4 pictures on the top of one of the png's i used as input to see the scale  :
![overlay input_output](https://user-images.githubusercontent.com/15131985/35299281-0f3d6656-0085-11e8-8345-5d9fee19f364.png)
Even the biggest one of the 4 is way too small to see anything with this scale honestly.

 I don't know if i is possible to have a kind of option/switch to select the output number of pics or scale or additionally have and option to generate a same resolution picture as the input images compared, a bit like it was before.

Thank you i understand now why the results are different.

I fixed the other issue i had, something was going wrong with my batch automated script due to the score decimal change but i was too tired after putting some time testing various things on the new version of Dssim to see it before, sorry for that,  now i get it working as before which is nice to automate comparisons.

Thanks a lot for having take the time to answer, i can only hope something could be done one of those days to have bigger output size for pictures or some options to choose the scale and number of pictures for the -o option.

Thanks again.

**Comment by kornelski** [comment]
You should get one output file at full resolution, and then next at half resolution, etc. I don't know why you're not getting them. I can't reproduce it in 2.9.4.

**Comment by kornelski** [comment]
I've released a newer version. Try that.

**Comment by jalba69** [comment]
Hello,
Just tried the new 2.9.7 version and now it works , i get one pic at full resolution 1280x522 px :
![dssim_24_01_2018- 1-22-06__0 010827 png-0](https://user-images.githubusercontent.com/15131985/35307875-514f4486-00a5-11e8-95d8-c681407e1cae.png)

the 3 others are 
640x261
320x130
160x65 for the smallest one

Don't know what you changed in this last build but it works now and it is perfect, 

Thank you very much for the quick reply and fix and for this great tool.
