### ISSUE TITLE
Impossible to compare RGBLU images (without alpha)

### ISSUE THREAD

**Issue by mateon1** [kornelski/dssim#47]
Trying to compile the file:
```rust
extern crate dssim;
extern crate imgref;

use dssim::{Dssim, RGBLU};
use imgref::{Img, ImgRef, ImgVec};

fn main() {
    let mut ctx = Dssim::new();
    let im: ImgVec<RGBLU> = Img::new(vec![], 0, 0);
    let imr: ImgRef<RGBLU> = im.as_ref();
    ctx.create_image(&imr);
}
```
gives me a
```rust
error[E0277]: the trait bound `imgref::Img<std::vec::Vec<rgb::RGB<f32>>>: dssim::ToLABBitmap` is not satisfied
  --> src/main.rs:14:9
   |
14 |     ctx.create_image(&imr);
   |         ^^^^^^^^^^^^ the trait `dssim::ToLABBitmap` is not implemented for `imgref::Img<std::vec::Vec<rgb::RGB<f32>>>`
   |
   = help: the following implementations were found:
             <imgref::Img<std::vec::Vec<rgb::RGBA<f32>>> as dssim::ToLABBitmap>
             <imgref::Img<&'a [rgb::RGBA<f32>]> as dssim::ToLABBitmap>
             <imgref::Img<&'a [rgb::RGB<f32>]> as dssim::ToLABBitmap>
             <imgref::Img<std::vec::Vec<f32>> as dssim::ToLABBitmap>
```
error.

The error message is extremely confusing, but:
The type signature of `create_image` is essentially
```rust
fn create_image<In, Out>(bitmap: &In) -> ...
  where
    In:  ToLABBitmap + Downsample<Output=Out>,
    Out: ToLABBitmap + Downsample<Output=Out>,
```

`ToLABBitmap` is implemented for `ImgVec<RGBAPLU>, ImgVec<f32>, ImgRef<RGBAPLU>` and `ImgRef<RGBLU>`
But it's not implemented for `ImgVec<RGBLU>`.

`Downsample` has `Output=ImgVec<RGBLU>` for `ImgRef<RGBLU>`, so providing an ImgRef as the `In` type in `create_image` makes `Out = ImgVec<RGBLU>`, for which `ToLABBitmap` is unimplemented.

I assume this is unintentional.

I believe the fix should be implementing `ToLABBitmap` for `ImgVec<RGBLU>`, (and possibly `ImgRef<f32>` - those impls are not symmetrical)

As a sidenote, there is no `ToRGBLU` trait, so working with RGB values is less nice than RGBA values.

**Comment by kornelski** [comment]
Use `imgvec.as_ref()` to get `ImgRef` out of it (it's analogous to `String.as_str()` to work with `&str`-only implementations).

**Comment by kornelski** [comment]
Ah, I see. Fixed.
