### ISSUE TITLE
Run dssim on Windows

### ISSUE THREAD

**Issue by Davide57** [kornelski/dssim#50]
Hi, how to run it on Windows? I installed libpng(http://gnuwin32.sourceforge.net/packages/libpng.htm) but running the command 
`dssim file-original.png file-modified.png`
the command dssim is not recognized...
How can I solve?

**Comment by kornelski** [comment]
"command not recognized" means the directory you're in doesn't have dssim.exe 

Use `cd` to change to the directory where `dssim.exe` is.

**Comment by Davide57** [comment]
Yes but there's no .exe file in your repo. Are we supposed to take it anywhere else?

**Comment by kornelski** [comment]
There's a ZIP file attached on Releases page. `win` folder has `dssim.exe`.

If you want to build it yourself:

1. Install Visual Studio 2015 or 2017 with support for Windows 8 SDK
2. Install Rust
3. Clone this repo
4. Run `cargo build --release` or `cargo run --release` in the repo directory

**Comment by Davide57** [comment]
I runned it successfully but it works only with png images. I really need to run it with .tif images, is it possible?
