### ISSUE TITLE
Images with different dimensions

### ISSUE THREAD

**Issue by Mike-Neto** [kornelski/dssim#52]
When comparing images with different dimensions we trigger the debug assert in impl Channable<f32, f32> for DssimChan<f32> 

So I was looking into fixing this issue either by changing the visibility of DssimImage & DssimChanScale's proprieties to public so I can inspect the sizes before calling into Dssim::compare.

Or to change it on the Dssim side by either returning Dssim(1.0) or whatever flag value inside Dssim itself.

What approach you think it's best?

I will make a PR for the fist approach as it's a lot less work and adds a lot more flexibility to use this crate as a lib.

**Comment by kornelski** [comment]
Why do you need this? I'm expecting that you check image dimensions before giving them to the library.

There's no way to meaningfully compare images with different dimensions, so the library intentionally treats this as programmer's error.

**Comment by Mike-Neto** [comment]
I agree, there's no meaningful compare between images wit different dimensions, the thing is the image is loaded by dssim crate itself, so if you don't expose a way for me to get the dimensions from the loaded image, I would have to load it again myself to check and then let dssim load it again

**Comment by kornelski** [comment]
I don't see where it's the limitation. 

The library is unable to load images itself. It takes an in-memory bitmap with known dimensions.

**Comment by Mike-Neto** [comment]
My Bad, I now saw that I do read the image from disk myself already, thanks for the info.

You can close this and decline the PR, Thanks.
