### ISSUE TITLE
Error message during Compiling of dssim

### ISSUE THREAD

**Issue by Patman86** [kornelski/dssim#72]
Hello, I get the following error message when I try to compile dssim:

`# cargo build --release
   Compiling mozjpeg-sys v0.10.5
error: linking with `gcc` failed: exit code: 1
  |
  = note: "gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-nostdlib" "-m64" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\dllcrt2.o" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\deps\\mozjpeg_sys-648e1100be522e84.mozjpeg_sys.5z8axcoy-cgu.0.rcgu.o" "-o" "D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\deps\\mozjpeg_sys-648e1100be522e84.dll" "-Wl,--version-script=C:\\Users\\PATRIC~1\\AppData\\Local\\Temp\\rustcdT3FW4\\list" "D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\deps\\mozjpeg_sys-648e1100be522e84.3ut8t4tviab954pf.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\deps" "-L" "D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\build\\mozjpeg-sys-b5e493b230603ec9\\out" "-L" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "-Wl,--whole-archive" "-lmozjpeg62" "-Wl,--no-whole-archive" "D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\deps\\liblibc-9eeb32fa6e1507b1.rlib" "-Wl,--start-group" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-2709d4b440f1e31a.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-a9004ff0947ef669.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-51ba26adca1c882c.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-845f51604911fcc4.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace-de041ab5ae3894b3.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libbacktrace_sys-583b927240902ae3.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-dc3974e5e5ee3f1e.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-93e1dea24f969698.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-59c69470ac86444e.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-5fe3f715aad021c1.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-289552190fa6ddd0.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-663fc4811d41d373.rlib" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-985f2d98a138c88e.rlib" "-Wl,--end-group" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-8d584b80572e52da.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-Wl,-Bstatic" "-lgcc_eh" "-lpthread" "-shared" "-Wl,--out-implib,D:\\Download\\m-ab-s\\build\\dssim-git\\target\\release\\deps\\mozjpeg_sys-648e1100be522e84.dll.lib" "-Wl,-Bdynamic" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\Pat Rick\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: D:\Download\m-ab-s\build\dssim-git\target\release\build\mozjpeg-sys-b5e493b230603ec9\out\libmozjpeg62.a(jcmaster.o):jcmaster.c:(.text$copy_buffer+0xd0): undefined reference to `__imp___acrt_iob_func'
          D:\Download\m-ab-s\build\dssim-git\target\release\build\mozjpeg-sys-b5e493b230603ec9\out\libmozjpeg62.a(jerror.o):jerror.c:(.text$output_message+0x1d): undefined reference to `__imp___acrt_iob_func'

error: aborting due to previous error

error: could not compile `mozjpeg-sys`.

To learn more, run the command again with --verbose.

**Comment by 1480c1** [comment]
feels like https://github.com/racer-rust/racer/issues/919

**Comment by Patman86** [comment]
could be possible

**Comment by kornelski** [comment]
Try using Rust's `-msvc` target instead of the `-gnu` target.
