### ISSUE TITLE
Can’t compile to WebAssembly

### ISSUE THREAD

**Issue by surma** [kornelski/dssim#78]
The `dssim` CLI depends on the `load_image` crate which in turn relies on multiple `*-sys` crates. This makes compilation to WebAssembly fail. I am not sure why `crate` is compiling the CLI when I am only using it as a library, but it is. 

Would it be feasible to separate the CLI and library into separate crates? Or maybe another solution is to put the CLI behind a (default-enabled) feature?

**Comment by surma** [comment]
After taking a closer look, I am now aware that you are using `rayon`, which probably also poses a challenge for the WebAssembly target. Not sure how feasible it is to make `rayon` optional? 🤔

**Comment by kornelski** [comment]
If you write a `rayoff` crate that exposes same methods, but serial, then I'll add it as an option.

**Comment by kornelski** [comment]
I've published lib-only crate https://lib.rs/dssim-core

**Comment by surma** [comment]
> I've published lib-only crate lib.rs/dssim-core

That’s incredibly helpful. Thanks for that. I do like the idea of `rayoff` ;)

**Comment by surma** [comment]
Turns out, [`rayon` already compiles against wasm](https://github.com/rayon-rs/rayon/blob/9f7357befbe886d861b6d741a7a7be5348bca59b/.github/workflows/ci.yaml#L93). I am somewhat confident that your split just solved the entire problem. 

Testing that now…

**Comment by surma** [comment]
Yup. This is all I needed. This library can now be used in WebAssembly 🎉  Thanks for the ultra-quick turnarnound!
