### ISSUE TITLE
Latest scale weight is ignored

### ISSUE THREAD

**Issue by igv** [kornelski/dssim#87]
[Here](https://github.com/kornelski/dssim/blob/main/dssim-core/src/dssim.rs#L181), it should be `DEFAULT_WEIGHTS[0..5]` (indexing is start:end-1).

Also it would be handy if it was possible to specify the number of scales from a command line.

**Comment by igv** [comment]
Just for the record, mean absolute deviation pooling is a good alternative to a combination of local maximums and averages (I thought maybe that's the reason why you using only 4 scales).

**Comment by kornelski** [comment]
Thanks. I'll test it with more scales.
