### ISSUE TITLE
assertion failed: i <= 1.0 && i >= 0.0

### ISSUE THREAD

**Issue by mlwilkerson** [kornelski/dssim#94]
After updating to dssim 3.0.0 two of my tests fail with:

```
assertion failed: i <= 1.0 && i >= 0.0
```

One of them compares an image to itself, and the other compares that image to itself rotated by 90 degrees.

This failure seems to occur only when dssim is built in debug mode.

It can be reproduced by building the cli v3.0.0 in debug mode and running:

```
$ dssim beer-solid.png beer-solid.png
```

or

```
$ dssim beer-solid.png beer-solid-sideways.png
```

If the cli is built in release mode and the same commands are run, the process completes as expected, reporting the dssim values: 0.00075077 and 1.64705301, respectively.

These images are rendered from the Font Awesome Free [`beer` icon](https://github.com/FortAwesome/Font-Awesome/blob/master/svgs/solid/beer.svg) in the Solid style.

> Font Awesome Free 5.15.2 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)

![beer-solid-sideways](https://user-images.githubusercontent.com/11575183/109692228-204beb80-7b3d-11eb-8194-cd4ead9d9e5c.png)
![beer-solid](https://user-images.githubusercontent.com/11575183/109692231-20e48200-7b3d-11eb-8157-55cdeedc2751.png)

**Comment by kornelski** [comment]
I can't reproduce. Can you attach the actual images you use?

**Comment by mlwilkerson** [comment]
Oh, whoops! Yeah, I had intended to attach those. I've updated the original post with them.

**Comment by kornelski** [comment]
Thanks. It turns out that if you add `* 1.1` to an algorithm, you get numbers larger than 1.0. Who knew!?

**Comment by mlwilkerson** [comment]
awesome. thank you.
